
POST http://localhost:3000/users/signup
Content-Type: "application/json"

{
    "email": "fezrza",
    "password": "fezrza",
    "name": "fezrza"
}

###

POST http://localhost:3000/posts/add
Content-Type: "application/json"

{
    "message": "zerazerazerez"
}